### ISSUE TITLE
Add link to godoc

### ISSUE THREAD

**Issue by johnsiilver** [pawelgaczynski/giouring#2]
I added this project to pkg.go.dev:
https://pkg.go.dev/github.com/pawelgaczynski/giouring

Here's the link for the readme:

[![GoDev](https://img.shields.io/static/v1?label=godev&message=reference&color=00add8)](https://pkg.go.dev/github.com/pawelgaczynski/giouring)

Cheers and thanks for providing this!

**Comment by pawelgaczynski** [comment]
I have added a link to the documentation. Thank you
